cli-next: Report build errors during release
Summary:
Prior to this commit, the CLI's "release" sub-command did not detect
failures that occurred while building the code. The process ultimately
failed because the subsequent uploading operation could not proceed
in the absence of a file to upload, but the output presented to
end-users obscured the source of the problem. For instance:

    $ echo '/*' >> frontend/index.js
    $ ../../packages/cli-next/bin/run release
    Bundling... done
    Uploading... Incomplete
    Error: ENOENT: no such file or directory, open '/home/sally/blocks-sdk/examples/todo-block/.tmp/dist/bundle.js'
    $ echo $?
    1

With this patch applied, the CLI correctly identifies build failures and
immediately reports reports diagnostic information:

    $ echo '/*' >> frontend/index.js
    $ ../../packages/cli-next/bin/run release
    Bundling... Incomplete
    ModuleBuildError: Module build failed (from ../../packages/cli-next/node_modules/babel-loader/lib/index.js):
    SyntaxError: /home/sally/blocks-sdk/examples/todo-block/frontend/index.js: Unterminated comment (7:0)
      5 |
      6 | initializeBlock(() => <TodoApp />);
    > 7 | /*
        | ^
      8 |
        at _temp._raise (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/parser/error.js:97:45)
        at _temp.raiseWithData (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/parser/error.js:92:17)
        at _temp.raise (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/parser/error.js:41:17)
        at _temp.skipBlockComment (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/tokenizer/index.js:276:32)
        at _temp.skipBlockComment (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/plugins/flow.js:3074:13)
        at _temp.skipSpace (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/tokenizer/index.js:357:20)
        at _temp.nextToken (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/tokenizer/index.js:235:42)
        at _temp.next (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/tokenizer/index.js:158:10)
        at _temp.eat (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/tokenizer/index.js:165:12)
        at _temp.isLineTerminator (~/sally/blocks-sdk/packages/cli-next/node_modules/@babel/parser/src/parser/util.js:102:17)
        at processResult (~/sally/blocks-sdk/packages/cli-next/node_modules/webpack/lib/NormalModule.js:583:19)
        at ~/sally/blocks-sdk/packages/cli-next/node_modules/webpack/lib/NormalModule.js:676:5
        at ~/sally/blocks-sdk/packages/cli-next/node_modules/loader-runner/lib/LoaderRunner.js:397:11
        at ~/sally/blocks-sdk/packages/cli-next/node_modules/loader-runner/lib/LoaderRunner.js:252:18
        at context.callback (~/sally/blocks-sdk/packages/cli-next/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
        at ~/sally/blocks-sdk/packages/cli-next/node_modules/babel-loader/lib/index.js:59:103
    $ echo $?
    1

Test Plan:
1. Insert invalid syntax into the source code of a App that the CLI is
   otherwise capable to release successfully.
2. Attempt to release the modified App.
3. Verify that the CLI reports the "Bundling" operation to be
   "Incomplete" and that it writes relevant diagnostic information to
   the process's standard error stream.

Reviewers: benrazon, mzgoddard, somehats

Reviewed By: benrazon

Differential Revision: https://airtable.phacility.com/D29917