Blocks Testing: update @airtable/blocks dependency to latest version
Summary:
When trying to use the @airtable/blocks-testing library today, Kate noticed the
following error:
Cannot find module '@airtable/blocks/unstable_testing_utils' from 'node_modules/@airtable/blocks-testing/dist/cjs/vacant_airtable_interface.js'
I believe this is due to a version incomaptability issue with the blocks sdk version since 1.4.1
is before the creation of unstable_testing_utils and was added in 1.5.0.

Test Plan:
I'm not really sure how to test this. Updating this caused my tests to pass locally with npm link,
but when I ran yarn install for the whole repo, that also fixed the tests locally.

Reviewers: somehats, jugglinmike

Reviewed By: somehats

Differential Revision: https://airtable.phacility.com/D28886