cli: Add 'junction' arg for fs symlink for Windows
Summary:
Why
===
In Windows, if you're using CMD.exe (the Command Prompt) as a non-Administrator role, then `block release` will fail with the following error:

```
Error: EPERM: operation not permitted, symlink 'C:\Users\airtable\AppData\Local\Temp\build\1565819618057\src\user\frontend' -> 'C:\Users\airtable\AppData\Local\Temp\build\1565819618057\src\user\node_modules\frontend'
```

Google searching around, found the following notes:
> `fs.symlink` appears to require admin privileges on Windows 10 for some reason. If anyone else runs into this, try running as admin.
src: https://github.com/nodejs/node/issues/18518#issuecomment-513809856

> FWIW, I actually needed to pass `type=junction` to `fs.symlink`, that made running as admin unnecessary and made the symlinks actually work.
src: https://github.com/nodejs/node/issues/18518#issuecomment-513866491

In Windows, the difference between symlinks, hard links, and junctions (though admittedly, not sure if I 100% grok it):
* https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions
* https://superuser.com/questions/343074/directory-junction-vs-directory-symbolic-link/343079#343079

What
====
* As mentioned above, passing in `junction` arg allows the symlinking to work without being an Administrator. Therefore, the fix is to pass in the `junction` arg in our usage of `fs.symlink`.

Also, for non-Windows platforms, this arg will be ignored so we can always pass it in without having to check for the user's OS:
> The type argument is only available on Windows and ignored on other platforms. It can be set to `'dir'`, `'file'`, or `'junction'`.
src: https://nodejs.org/api/fs.html#fs_fs_symlink_target_path_type_callback

Tested manually:

Screenshot - {F130179}

Test Plan:
* In Windows, open Command Prompt in non-Adminstrator mode. In the typical case, this should just be default way to open the Command Prompt.
* Navigate to a block directory
* Run `block release` -> block should release successfully.

Reviewers: jichu4n, kasrak

Reviewed By: jichu4n

Differential Revision: https://airtable.phacility.com/D11180