Cli-next: Check for errors in webpack compilation when finding dependencies for submit task (#72)
Commitment: https://airtable.com/appahuJQw7qfQTBBU/tblSbpimM8Spp9txp/viwq3i77XPtAQxZfp/recw6JhHc2k6oC8Ce?blocks=hide

A couple months ago, we had a developer submit an app without installing dependencies. More generally, it's currently possible to submit an app which has compilation errors. This change builds on the work in https://github.com/Hyperbase/blocks-sdk/pull/70 which will allow us to simply throw any compilation errors we get from webpack, and the developer will see the error in their console.

### Testing
Create a custom app, and delete node_modules. Run
```
$ <path-to-cli-next>/bin/run submit
```

Example output:
```
Finding dependencies... Incomplete
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/server' in '/Users/kevin.wilde/h/source/test_blocks_v_2_app_should_create_metadata_row/.tmp'
    at ~/h/source/blocks-sdk/packages/cli-next/node_modules/webpack/lib/Compilation.js:1586:28
    at ~/h/source/blocks-sdk/packages/cli-next/node_modules/webpack/lib/NormalModuleFactory.js:648:13
    at eval (eval at create (/Users/kevin.wilde/h/source/blocks-sdk/packages/cli-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at ~/h/source/blocks-sdk/packages/cli-next/node_modules/webpack/lib/NormalModuleFactory.js:233:22
    at eval (eval at create (/Users/kevin.wilde/h/source/blocks-sdk/packages/cli-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at ~/h/source/blocks-sdk/packages/cli-next/node_modules/webpack/lib/NormalModuleFactory.js:357:22
    at ~/h/source/blocks-sdk/packages/cli-next/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at ~/h/source/blocks-sdk/packages/cli-next/node_modules/webpack/lib/NormalModuleFactory.js:577:24
    at ~/h/source/blocks-sdk/packages/cli-next/node_modules/webpack/lib/NormalModuleFactory.js:721:5
    at finishWithoutResolve (~/h/source/blocks-sdk/packages/cli-next/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
```