Cli-next: Fix serialization of errors from child process (#70)
### Background

1. Cli-next runs the bundler in a separate process using `child_process.fork` ([code](https://github.com/Hyperbase/blocks-sdk/blob/132210e94/packages/cli-next/src/helpers/fork_task_async.ts#L15)). The bundler process communicates with the parent cli process over a `Channel` object, which ultimately uses the node Processes to send and receive messages via the `send` method ([ref](https://nodejs.org/api/child_process.html#child_process_subprocess_send_message_sendhandle_options_callback)) and the `'message'` event ([ref](https://nodejs.org/api/process.html#process_event_message)) respectively. The key thing to know is that 
   > The message goes through serialization and parsing.

2. The next thing to know is that all of the properties on `Error` are non-[enumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties).
```
Object.keys(new Error()).length === 0
```

3. The last thing to know is that when an object is serialized only its enumerable properties are serialized. (At least, that's true for [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) which appears to be what node uses by default for the serialization. See https://github.com/nodejs/help/issues/1533#issuecomment-500726292. When I run the example in that comment, I get an error on this line in node https://github.com/nodejs/node/blob/master/lib/internal/child_process/serialization.js#L127)

So putting this together, if we want to pass an error from the bundler process to the parent cli process and retain the message and stack, we should be sure to pass a serialized version rather than the actual `Error` object.

### Changes

- At the point where the child is sending an error message to the parent cli process, serialize the error.
- At the point where the parent receives an error message, deserialize it before throwing. Previously this was throwing a non-error object.
- Update one place in the bundler to throw an error object instead of a json representation of an error.

### Testing

Create a custom app and add a syntax error in the code. Run

```
$ <path-to-cli-next>/bin/run release
```

Example output:

```
Bundling... Incomplete
ModuleBuildError: Module build failed (from ../blocks-sdk/packages/cli-next/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/kevin.wilde/h/source/test_blocks_v_2_app_should_create_metadata_row/frontend/index.js: Unterminated comment (8:13)
   6 |     // YOUR CODE GOES HERE
>  7 |     return ( /* 
     |              ^
   8 |         <div>
   9 |             <div>Hello world!! 🚀</div>
```

Similarly, an error in the bundler itself will lead to the message and stack being shown in the console.