sdk: internal -> hidden on aggregators to fix scripting typechecking
Summary:
As per discussion with @somehats on Slack.

When trying to land D18470 using 0.0.50, typecheck fails:

```  typescript
node_modules/@airtable/blocks/dist/types/src/models/models.d.ts(15,44): error TS2344: Type 'typeof import("/Users/emma/h/source/hyperbase_development/node_modules/@airtable/blocks/dist/types/src/models/create_aggregators")' does not satisfy the constraint '(...args: any) => any'.
  Type 'typeof import("/Users/emma/h/source/hyperbase_development/node_modules/@airtable/blocks/dist/types/src/models/create_aggregators")' provides no match for the signature '(...args: any): any'.
```

This is because types for `@internal` things are stripped out, but they're required to determine other, public types that the scripting block relies on.

Test Plan: N/A

Reviewers: somehats

Reviewed By: somehats

Subscribers: somehats

Differential Revision: https://airtable.phacility.com/D18665