cli-next: strip flow types
Summary:
Add the babel flow-strip-types transform plugin. The current cli uses this
plugin to strip flow types from js files. Without this, existing blocks with flow
types will throw an error when babel parses those js files containing flow
types.

- Add a unit test with flow types that must build

Test Plan:
- Run `block run` in the Page Designer or CSV Import block
- Before this change expect an error like:

> ```
> Module build failed (from ../../blocks-sdk/packages/cli-next/node_modules/babel-loader/lib/index.js):
> SyntaxError: ~/blocks/csv_import/frontend/FileDropper.js: Unexpected token (9:14)
>
>    7 |
>    8 | class FileDropper extends React.Component {
>>  9 |     _fileInput: HTMLInputElement;
>      |               ^
>   10 |
>   11 |     state = {
>   12 |         isMousingOver: false,
> ```

- After this change expect to not see the above error. Instead there should now be errors like these:

> ```
> Module not found: Error: Can't resolve 'stream' in '~/blocks/csv_import/node_modules/csv-string/lib'
>
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
>
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
> 	- install 'stream-browserify'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "stream": false }
> ```

> ```
> Uncaught TypeError: (0 , _pica__WEBPACK_IMPORTED_MODULE_1__.default) is not a function
>     at eval (webpack://@airtable/blocks-page_designer/./frontend/image_resizer.js?:16)
>     at Module../frontend/image_resizer.js (localhost:9000/__runFrame/bundle.js:487)
>     at __webpack_require__ (localhost:9000/__runFrame/bundle.js:11564)
>     at eval (webpack://@airtable/blocks-page_designer/./frontend/container_with_view.js?:34)
>     at Module../frontend/container_with_view.js (localhost:9000/__runFrame/bundle.js:224)
>     at __webpack_require__ (localhost:9000/__runFrame/bundle.js:11564)
>     at eval (webpack://@airtable/blocks-page_designer/./frontend/container_with_table.js?:15)
>     at Module../frontend/container_with_table.js (localhost:9000/__runFrame/bundle.js:209)
>     at __webpack_require__ (localhost:9000/__runFrame/bundle.js:11564)
>     at eval (webpack://@airtable/blocks-page_designer/./frontend/main.js?:11)
> ```

Reviewers: somehats, jugglinmike, benrazon

Reviewed By: benrazon

Differential Revision: https://airtable.phacility.com/D28507